name: ap2025-maxime
channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - numpy=2.4.0
  - pandas=2.3.3
  - scikit-learn=1.8.0
  - xgboost=3.1.2
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - streamlit>=1.28
  - openpyxl=3.1.5
  - pyyaml=6.0.3
  - pip
  - pip:
    - packaging>=21.0